language: node_js
dist: trusty
node_js:
  - "10"
install:
  - npm i
  - git clone https://github.com/ChenYFan/CheckSSL --depth=2
script:
  - npm run build
  - cd CheckSSL
  - chmod +x checker.sh
  - ./checker.sh blog.cyfan.top cyfan.top status.cyfan.top tools.cyfan.top so.cyfan.top www.cyfan.top api.cyfan.top pan.cyfan.top cdn.cyfan.top ssl.cyfan.top pixiv.cyfan.top pixiv-img.cyfan.top
  - cp -rf ./output/ct.json ../public/ct.json
  - echo "xiaossl.xiao811.eu.org" > ../public/CNAME
branches:
  only:
    - master
cache:
  directories:
    - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  target_branch: gh-pages
  email: $GITHUB_EMAIL
  name: $GITHUB_USER
  local-dir: public
  on:
    branch: master
